[project]
name = "safe"
version = "0.1.0"
description = "A decentralized CLI for Safe Smart Accounts"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "click>=8.2.1",
  "pydantic>=2.11.4",
  "rich>=14.0.0",
  "safe-eth-py>=7.3.0",
]

[project.scripts]
safe = "safe:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
